export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_INIT = 'LOGIN_INIT';

//redux-saga ver
export const LOGIN_INIT_REQUEST = 'LOGIN_INIT_REQUEST';
export const LOGIN_INIT_SUCCESS = 'LOGIN_INIT_SUCCESS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const GET_ALL_USER_REQUEST = 'GET_ALL_USER_REQUEST';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const CHANGE_ALL_USER_ONLINE = 'CHANGE_ALL_USER_ONLINE';

export const CONNECT_SOCKET_INIT_REQUEST = 'CONNECT_SOCKET_INIT_REQUEST';
export const CONNECT_SOCKET_INIT_SUCCESS = 'CONNECT_SOCKET_INIT_SUCCESS';

export const BROADCASTING = 'BROADCASTING';
export const SEND_TO_ALL_MSG = 'SEND_TO_ALL_MSG';
export const PUBLIC_CHAT_LOG = 'PUBLIC_CHAT_LOG';
export const PUBLIC_CHAT_LOG_ORIGIN_REQUEST = 'PUBLIC_CHAT_LOG_ORIGIN_REQUEST';
export const PUBLIC_CHAT_LOG_ORIGIN = 'PUBLIC_CHAT_LOG_ORIGIN';

/* PRIVATE TYPE */
export const REQUEST_CREATE_ROOM = 'REQUEST_CREATE_ROOM';
export const SUCCESS_CREATE_ROOM = 'SUCCESS_CREATE_ROOM';
export const ADD_PRIVATE_ROOM = 'ADD_PRIVATE_ROOM';
export const SEND_PRIVATE_MSG = 'SEND_PRIVATE_MSG';
export const RECEIVE_PRIVATE_MSG = 'RECEIVE_PRIVATE_MSG';
export const ADD_PRIVATE_MSG = 'ADD_PRIVATE_MSG';
