export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_INIT = 'LOGIN_INIT';

//redux-saga ver
export const LOGIN_INIT_REQUEST = 'LOGIN_INIT_REQUEST';
export const LOGIN_INIT_SUCCESS = 'LOGIN_INIT_SUCCESS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const GET_ALL_USER_REQUEST = 'GET_ALL_USER_REQUEST';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const CHANGE_ALL_USER_ONLINE = 'CHANGE_ALL_USER_ONLINE';

export const CONNECT_SOCKET_INIT_REQUEST = 'CONNECT_SOCKET_INIT_REQUEST';
export const CONNECT_SOCKET_INIT_SUCCESS = 'CONNECT_SOCKET_INIT_SUCCESS';

export const BROADCASTING = 'BROADCASTING';
